"""crear el modelo carrito

Revision ID: 1afeb5430809
Revises: 242a0c3c756b
Create Date: 2021-03-04 15:47:51.749220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1afeb5430809'
down_revision = '242a0c3c756b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrito',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrito_cantidad'), 'carrito', ['cantidad'], unique=False)
    op.create_index(op.f('ix_carrito_price'), 'carrito', ['price'], unique=False)
    op.create_index(op.f('ix_carrito_subtotal'), 'carrito', ['subtotal'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carrito_subtotal'), table_name='carrito')
    op.drop_index(op.f('ix_carrito_price'), table_name='carrito')
    op.drop_index(op.f('ix_carrito_cantidad'), table_name='carrito')
    op.drop_table('carrito')
    # ### end Alembic commands ###
