""" agregar estado al modelo producto

Revision ID: 242a0c3c756b
Revises: 720b60cef9c2
Create Date: 2021-03-04 13:45:07.195566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242a0c3c756b'
down_revision = '720b60cef9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('status', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_column('products', 'status')
    # ### end Alembic commands ###
